### ISSUE TITLE
Upgrade Web Request Logger to Liferay Portal 7.0.0 CE A1

### ISSUE THREAD

**Issue by timtelcik** [permeance/liferay-web-request-logger#2]
Upgrade Web Request Logger to Liferay Portal 7.0.0 CE A1.

**Comment by timtelcik** [comment]
**Changes Fri 09 Oct 2015**
- Merge changes from LP 7.0.0 CE A1 (7.0.0).
- Tested Web Request Logger with LP 7.0 CE A1 + TC bundle.
- Uploaded Web Request Logger plugin for LP 7.0 CE A1 to Source Forge.

**Comment by timtelcik** [comment]
##Web Request Logger does not deploy to Liferay Portal 7.0.0 CE A1

###Portal Error Log
    
    07:33:25,100 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:203] Processing web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war
    07:33:25,103 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:69] Deploying package as a web application
    07:33:25,103 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:79] Copying portlets for /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/deploy/web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war
    07:33:25,115 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][BaseDeployer:878] Deploying web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war
      Expanding: /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/deploy/web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war into /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/tomcat/temp/20151009073325115
      Copying 1 file to /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/tomcat/temp/20151009073325115/WEB-INF/classes
      Copying 1 file to /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/tomcat/temp/20151009073325115/WEB-INF/classes
      Copying 1 file to /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/tomcat/temp/20151009073325115/WEB-INF/jsp
    07:33:25,148 ERROR [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:219] com.liferay.portal.kernel.deploy.auto.AutoDeployException: java.lang.NullPointerException
    com.liferay.portal.kernel.deploy.auto.AutoDeployException: java.lang.NullPointerException
    	at com.liferay.portal.tools.deploy.BaseDeployer.autoDeploy(BaseDeployer.java:214)
    	at com.liferay.portal.deploy.auto.ThreadSafeAutoDeployer.autoDeploy(ThreadSafeAutoDeployer.java:36)
    	at com.liferay.portal.deploy.auto.PortletAutoDeployListener.deploy(PortletAutoDeployListener.java:88)
    	at com.liferay.portal.kernel.deploy.auto.AutoDeployDir.deploy(AutoDeployDir.java:50)
    	at com.liferay.portal.kernel.deploy.auto.AutoDeployDir.processFile(AutoDeployDir.java:210)
    	at com.liferay.portal.kernel.deploy.auto.AutoDeployDir.scanDirectory(AutoDeployDir.java:274)
    	at com.liferay.portal.kernel.deploy.auto.AutoDeployScanner.run(AutoDeployScanner.java:58)
    Caused by: java.lang.NullPointerException
    	at com.liferay.portal.deploy.auto.WAIAutoDeployer.copyXmls(WAIAutoDeployer.java:74)
    	at com.liferay.portal.tools.deploy.BaseDeployer.deployDirectory(BaseDeployer.java:673)
    	at com.liferay.portal.tools.deploy.BaseDeployer.deployFile(BaseDeployer.java:1081)
    	at com.liferay.portal.tools.deploy.BaseDeployer.deployFile(BaseDeployer.java:1013)
    	at com.liferay.portal.tools.deploy.BaseDeployer.autoDeploy(BaseDeployer.java:211)
    	... 6 more
    07:33:25,148 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:223] Add web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war to the blacklist
