### ISSUE TITLE
Web Request Logger does not deploy to Liferay Portal 7.0.0 CE A1

### ISSUE THREAD

**Issue by timtelcik** [permeance/liferay-web-request-logger#3]
##### Issue

Liferay Portal 7.0.0 CE A1 will not deploy Web Request Logger from plugin file named "web-request-logger-hook-1.0.1.1-7.0.x.war".
##### Portal Error Log

```
07:33:25,100 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:203] Processing web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war
07:33:25,103 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:69] Deploying package as a web application
07:33:25,103 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:79] Copying portlets for /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/deploy/web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war
07:33:25,115 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][BaseDeployer:878] Deploying web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war
  Expanding: /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/deploy/web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war into /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/tomcat/temp/20151009073325115
  Copying 1 file to /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/tomcat/temp/20151009073325115/WEB-INF/classes
  Copying 1 file to /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/tomcat/temp/20151009073325115/WEB-INF/classes
  Copying 1 file to /Users/tim.telcik/work/projects/permeance/liferay-marketplace/liferay-portal/liferay-portal-7.0-ce-a1/bundles/liferay-portal-7.0-ce-a1/tomcat/temp/20151009073325115/WEB-INF/jsp
07:33:25,148 ERROR [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:219] com.liferay.portal.kernel.deploy.auto.AutoDeployException: java.lang.NullPointerException
com.liferay.portal.kernel.deploy.auto.AutoDeployException: java.lang.NullPointerException
    at com.liferay.portal.tools.deploy.BaseDeployer.autoDeploy(BaseDeployer.java:214)
    at com.liferay.portal.deploy.auto.ThreadSafeAutoDeployer.autoDeploy(ThreadSafeAutoDeployer.java:36)
    at com.liferay.portal.deploy.auto.PortletAutoDeployListener.deploy(PortletAutoDeployListener.java:88)
    at com.liferay.portal.kernel.deploy.auto.AutoDeployDir.deploy(AutoDeployDir.java:50)
    at com.liferay.portal.kernel.deploy.auto.AutoDeployDir.processFile(AutoDeployDir.java:210)
    at com.liferay.portal.kernel.deploy.auto.AutoDeployDir.scanDirectory(AutoDeployDir.java:274)
    at com.liferay.portal.kernel.deploy.auto.AutoDeployScanner.run(AutoDeployScanner.java:58)
Caused by: java.lang.NullPointerException
    at com.liferay.portal.deploy.auto.WAIAutoDeployer.copyXmls(WAIAutoDeployer.java:74)
    at com.liferay.portal.tools.deploy.BaseDeployer.deployDirectory(BaseDeployer.java:673)
    at com.liferay.portal.tools.deploy.BaseDeployer.deployFile(BaseDeployer.java:1081)
    at com.liferay.portal.tools.deploy.BaseDeployer.deployFile(BaseDeployer.java:1013)
    at com.liferay.portal.tools.deploy.BaseDeployer.autoDeploy(BaseDeployer.java:211)
    ... 6 more
07:33:25,148 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:223] Add web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war to the blacklist
```

**Comment by timtelcik** [comment]
#### Update Fri 09 Oct 2015

##### Review
- Hook plugin deployment handled by method "deploy" in class "com.liferay.portal.deploy.auto.HookAutoDeployListener"
- Method "deploy" calls method "isHookPlugin" in base class "com.liferay.portal.kernel.deploy.auto.BaseAutoDeployListener"
- Method "isHookPlugin" does not recognise hook plugins with complex file names due to regex pattern "-(H|h)ook[-0-9.]_\+?\.(war|zip)$"
  *_ eg. "web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war"
- Method "isHookPlugin" does recognise simpler file names
  *\* eg. "web-request-logger-hook-1.0.1.1-7.0.0.war"

> ```
> public abstract class BaseAutoDeployListener implements AutoDeployListener {
>   public boolean isHookPlugin(File file) throws AutoDeployException {
>       Matcher matcher = _hookPluginPattern.matcher(file.getName());
> 
>       if (matcher.find() &&
>           isMatchingFile(file, "WEB-INF/liferay-hook.xml", false) &&
>           !isMatchingFile(file, "WEB-INF/liferay-portlet.xml", false)) {
> 
>           return true;
>       }
> 
>       return false;
>   }
> 
>   private static final Pattern _hookPluginPattern = Pattern.compile(
>       "-(H|h)ook[-0-9.]*\\+?\\.(war|zip)$");
> }     
> ```
- Hook plugin file name pattern matching added to LP 7.0 M7 as per LPS ticket LPS-56442
- LPS-56442 - When deploying a plugin, liferay-plugin-package.xml not get generated 
  - https://issues.liferay.com/browse/LPS-56442
- Changes in GitHub at
  - https://github.com/liferay/liferay-portal/commit/0f0a433914ac99440aa8348d5015021bc456b367

##### Solution
- Use hook plugin file name without alpha after version number
  - valid file name : web-request-logger-hook-1.0.1.1.war
  - valid file name : web-request-logger-hook-1.0.1.1-7.0.0.war
  - invalid file name : web-request-logger-hook-1.0.1.1-7.0.x.war
  - invalid file name : web-request-logger-hook-1.0.1.1-7.0.0-ce-a1.war

**Comment by timtelcik** [comment]
Summary posted to Liferay 7 Community Expedition forum at
- https://dev.liferay.com/web/liferay-7-community-expedition/feedback/-/message_boards/message/605714
